name: Build and release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./gui
    steps:
      # -------------------------
      # Setup
      # -------------------------
      
      - uses: actions/checkout@v4
      - name: Ensure script exists
        run: ls -R $env:GITHUB_WORKSPACE/.github/scripts

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install rinf
        run: cargo install rinf

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Generate message code
        run: rinf message

      # -------------------------
      # Setup windows
      # -------------------------

      - name: Setup Microsoft Store Developer CLI
        uses: microsoft/setup-msstore-cli@v1
    
      # ① GitHub Secrets から PFX を復元
      - name: Decode and save PFX certificate (Windows)
        run: |
          echo "${{ secrets.PFX_BASE64 }}" > encoded_cert.txt
          certutil -decode encoded_cert.txt test_certificate.pfx

      # ② PFX を Windows にインストール
      - name: Install signing certificate
        run: certutil -f -importpfx test_certificate.pfx -p revelation
        # run: |
        #   powershell -ExecutionPolicy Bypass -File .github/scripts/import_cert.ps1

      # ③ MSIX を作成（署名付き）
      - name: Create MSIX package
        run: |
          powershell -ExecutionPolicy Bypass -File "$env:GITHUB_WORKSPACE/.github/scripts/import_cert.ps1"

      - name: List files in the output directory
        run: |
          dir ./