name: Build and release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./gui
    steps:
      # -------------------------
      # Setup
      # -------------------------
      
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install rinf
        run: cargo install rinf

      - name: Generate message code
        run: rinf message

      # -------------------------
      # Setup windows
      # -------------------------

      - name: Setup Microsoft Store Developer CLI
        uses: microsoft/setup-msstore-cli@v1
    
      # ① GitHub Secrets から PFX を復元
      - name: Decode and save PFX certificate (Windows)
        run: |
          echo "${{ secrets.PFX_BASE64 }}" > encoded_cert.txt
          certutil -decode encoded_cert.txt test_certificate.pfx

      # ② PFX を Windows にインストール
      - name: Install signing certificate
        run: Start-Process PowerShell -ArgumentList "certutil -importpfx test_certificate.pfx -p 'revelation'" -Verb RunAs

      # ③ MSIX を作成（署名付き）
      - name: Create MSIX package
        run: Start-Process PowerShell -ArgumentList "dart run msix:create --certificate-path test_certificate.pfx --certificate-password 'revelation'" -Verb RunAs

      - name: List files in the output directory
        run: |
          dir ./dist/
          dir ./build/
          dir ./output/