name: Build and release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./gui
    steps:
      # -------------------------
      # Setup
      # -------------------------
      
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install rinf
        run: cargo install rinf

      - name: Generate message code
        run: rinf message

      # -------------------------
      # Setup windows
      # -------------------------

      - name: Setup Microsoft Store Developer CLI
        uses: microsoft/setup-msstore-cli@v1
      - name: Configure Microsoft Store Developer CLI
        run: msstore reconfigure --tenantId ${{ secrets.PARTNER_CENTER_TENANT_ID }} --sellerId ${{ secrets.PARTNER_CENTER_SELLER_ID }} --clientId ${{ secrets.PARTNER_CENTER_CLIENT_ID }} --clientSecret ${{ secrets.PARTNER_CENTER_CLIENT_SECRET }}

      # -------------------------
      # Build windows
      # -------------------------
      
      - name: Package windows
        run: dart run msix:create